---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    rebase-strategy: disabled
    versioning-strategy: increase-if-necessary
    assignees:
      - "tomerfi"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "ci"
    rebase-strategy: disabled
    assignees:
      - "tomerfi"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "docs"
      include: "scope"
    rebase-strategy: disabled
    versioning-strategy: increase-if-necessary
    assignees:
      - "tomerfi"
